export const POLL_STORAGE_ADDRESS = import.meta.env.VITE_POLL_STORAGE_ADDRESS as `0x${string}`;
export const POLL_CREATION_ADDRESS = import.meta.env.VITE_POLL_CREATION_ADDRESS as `0x${string}`;
export const VOTE_ACTION_ADDRESS = import.meta.env.VITE_VOTE_ACTION_ADDRESS as `0x${string}`;
export const RESULTS_READER_ADDRESS = import.meta.env.VITE_RESULTS_READER_ADDRESS as `0x${string}`;
export const QNS_REGISTRY_ADDRESS = import.meta.env.VITE_QNS_REGISTRY_ADDRESS as `0x${string}`;

export const POLL_STORAGE_ABI = [
  {
    inputs: [],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    inputs: [
      { internalType: 'address', name: '_contract', type: 'address' },
      { internalType: 'bool', name: '_status', type: 'bool' },
    ],
    name: 'setAuthorized',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_creator', type: 'address' },
      { internalType: 'string', name: '_question', type: 'string' },
      { internalType: 'string', name: '_description', type: 'string' },
      { internalType: 'string[]', name: '_options', type: 'string[]' },
      { internalType: 'uint256', name: '_startTime', type: 'uint256' },
      { internalType: 'uint256', name: '_endTime', type: 'uint256' },
      { internalType: 'uint8', name: '_eligType', type: 'uint8' },
      { internalType: 'address', name: '_eligToken', type: 'address' },
      { internalType: 'uint256', name: '_eligPodId', type: 'uint256' },
    ],
    name: 'createPoll',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_pollId', type: 'uint256' },
      { internalType: 'address', name: '_voter', type: 'address' },
      { internalType: 'uint256', name: '_optionIndex', type: 'uint256' },
    ],
    name: 'recordVote',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_pollId', type: 'uint256' }],
    name: 'getPoll',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'id', type: 'uint256' },
          { internalType: 'address', name: 'creator', type: 'address' },
          { internalType: 'string', name: 'question', type: 'string' },
          { internalType: 'string', name: 'description', type: 'string' },
          { internalType: 'string[]', name: 'options', type: 'string[]' },
          { internalType: 'uint256', name: 'startTime', type: 'uint256' },
          { internalType: 'uint256', name: 'endTime', type: 'uint256' },
          { internalType: 'uint8', name: 'eligibilityType', type: 'uint8' },
          { internalType: 'address', name: 'eligibilityToken', type: 'address' },
          { internalType: 'uint256', name: 'eligibilityPodId', type: 'uint256' },
          { internalType: 'bool', name: 'isListed', type: 'bool' },
          { internalType: 'uint256', name: 'totalVotes', type: 'uint256' },
        ],
        internalType: 'struct PollStorage.Poll',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_pollId', type: 'uint256' },
      { internalType: 'uint256', name: '_optionIndex', type: 'uint256' },
    ],
    name: 'getOptionVotes',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_pollId', type: 'uint256' },
      { internalType: 'address', name: '_voter', type: 'address' },
    ],
    name: 'getHasVoted',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_pollId', type: 'uint256' },
      { internalType: 'address', name: '_voter', type: 'address' },
    ],
    name: 'getVoterChoice',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_contract', type: 'address' }],
    name: 'getAuthorized',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'pollCount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_pollId', type: 'uint256' }],
    name: 'getPollVoters',
    outputs: [{ internalType: 'address[]', name: '', type: 'address[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_user', type: 'address' }],
    name: 'getUserPollsVoted',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_user', type: 'address' }],
    name: 'getUserPollsCreated',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'pollId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'creator', type: 'address' },
      { indexed: false, internalType: 'string', name: 'question', type: 'string' },
      { indexed: false, internalType: 'uint256', name: 'endTime', type: 'uint256' },
    ],
    name: 'PollCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'pollId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'voter', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'optionIndex', type: 'uint256' },
    ],
    name: 'VoteRecorded',
    type: 'event',
  },
] as const;

export const POLL_CREATION_ABI = [
  {
    inputs: [
      { internalType: 'address', name: '_pollStorage', type: 'address' },
      { internalType: 'address', name: '_qnsContract', type: 'address' },
      { internalType: 'address', name: '_treasury', type: 'address' },
      { internalType: 'address', name: '_burnAddress', type: 'address' },
      { internalType: 'uint256', name: '_creationFee', type: 'uint256' },
      { internalType: 'uint16', name: '_treasuryBps', type: 'uint16' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    inputs: [
      { internalType: 'string', name: '_question', type: 'string' },
      { internalType: 'string', name: '_description', type: 'string' },
      { internalType: 'string[]', name: '_options', type: 'string[]' },
      { internalType: 'uint8', name: '_durationDays', type: 'uint8' },
      { internalType: 'uint8', name: '_eligType', type: 'uint8' },
      { internalType: 'address', name: '_eligToken', type: 'address' },
      { internalType: 'uint256', name: '_eligPodId', type: 'uint256' },
    ],
    name: 'createPoll',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: '_question', type: 'string' },
      { internalType: 'string', name: '_description', type: 'string' },
      { internalType: 'string[]', name: '_options', type: 'string[]' },
      { internalType: 'uint256', name: '_endTimestamp', type: 'uint256' },
      { internalType: 'uint8', name: '_eligType', type: 'uint8' },
      { internalType: 'address', name: '_eligToken', type: 'address' },
      { internalType: 'uint256', name: '_eligPodId', type: 'uint256' },
    ],
    name: 'createPollCustomDuration',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_addr', type: 'address' },
      { internalType: 'bool', name: '_exempt', type: 'bool' },
    ],
    name: 'setExempt',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_fee', type: 'uint256' }],
    name: 'setCreationFee',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint16', name: '_bps', type: 'uint16' }],
    name: 'setTreasuryBps',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_treasury', type: 'address' }],
    name: 'setTreasury',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'pollStorage',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'qnsContract',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'treasury',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'burnAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'creationFee',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'treasuryBps',
    outputs: [{ internalType: 'uint16', name: '', type: 'uint16' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'exemptAddresses',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'pollId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'creator', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'feePaid', type: 'uint256' },
    ],
    name: 'PollCreatedWithFee',
    type: 'event',
  },
] as const;

export const VOTE_ACTION_ABI = [
  {
    inputs: [
      { internalType: 'address', name: '_pollStorage', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_pollId', type: 'uint256' },
      { internalType: 'uint256', name: '_optionIndex', type: 'uint256' },
    ],
    name: 'vote',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_qflink', type: 'address' }],
    name: 'setQFLinkContract',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_minBalance', type: 'uint256' }],
    name: 'setMinQFBalance',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'pollStorage',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'qflinkContract',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'minQFBalance',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'pollId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'voter', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'optionIndex', type: 'uint256' },
    ],
    name: 'VoteCast',
    type: 'event',
  },
] as const;

export const RESULTS_READER_ABI = [
  {
    inputs: [{ internalType: 'address', name: '_pollStorage', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_pollId', type: 'uint256' }],
    name: 'getPollResults',
    outputs: [
      {
        components: [
          { internalType: 'string', name: 'question', type: 'string' },
          { internalType: 'string', name: 'description', type: 'string' },
          { internalType: 'string[]', name: 'options', type: 'string[]' },
          { internalType: 'uint256[]', name: 'voteCounts', type: 'uint256[]' },
          { internalType: 'uint256', name: 'totalVotes', type: 'uint256' },
          { internalType: 'uint256[]', name: 'percentages', type: 'uint256[]' },
          { internalType: 'uint256', name: 'leadingOptionIndex', type: 'uint256' },
          { internalType: 'bool', name: 'isActive', type: 'bool' },
        ],
        internalType: 'struct ResultsReader.PollResults',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_offset', type: 'uint256' },
      { internalType: 'uint256', name: '_limit', type: 'uint256' },
    ],
    name: 'getPollList',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'id', type: 'uint256' },
          { internalType: 'string', name: 'question', type: 'string' },
          { internalType: 'address', name: 'creator', type: 'address' },
          { internalType: 'uint256', name: 'totalVotes', type: 'uint256' },
          { internalType: 'uint256', name: 'endTime', type: 'uint256' },
          { internalType: 'bool', name: 'isActive', type: 'bool' },
        ],
        internalType: 'struct ResultsReader.PollSummary[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getActivePollCount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_user', type: 'address' },
      { internalType: 'uint256', name: '_offset', type: 'uint256' },
      { internalType: 'uint256', name: '_limit', type: 'uint256' },
    ],
    name: 'getUserVotes',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'pollId', type: 'uint256' },
          { internalType: 'uint256', name: 'optionIndex', type: 'uint256' },
        ],
        internalType: 'struct ResultsReader.UserVote[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_user', type: 'address' }],
    name: 'getUserVoteCount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_user', type: 'address' }],
    name: 'getUserCreatedCount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_pollId', type: 'uint256' },
      { internalType: 'uint256', name: '_offset', type: 'uint256' },
      { internalType: 'uint256', name: '_limit', type: 'uint256' },
    ],
    name: 'getVoterList',
    outputs: [{ internalType: 'address[]', name: '', type: 'address[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_pollId', type: 'uint256' }],
    name: 'getVoterCount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const;

export const QFLINK_POLL_BRIDGE_ABI = [
  {
    inputs: [
      { internalType: 'address', name: '_pollCreation', type: 'address' },
      { internalType: 'address', name: '_qflinkRevenue', type: 'address' },
      { internalType: 'uint256', name: '_qflinkFee', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_podId', type: 'uint256' },
      { internalType: 'string', name: '_question', type: 'string' },
      { internalType: 'string[]', name: '_options', type: 'string[]' },
      { internalType: 'uint8', name: '_durationDays', type: 'uint8' },
    ],
    name: 'createPodPoll',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_fee', type: 'uint256' }],
    name: 'setQFLinkFee',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_addr', type: 'address' }],
    name: 'setQFLinkRevenue',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_qflink', type: 'address' }],
    name: 'setQFLinkContract',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'pollCreation',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'qflinkRevenue',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'qflinkFee',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const;
